aplikasi_chat/website/models/group.py
from website import db

class Group(db.Model):
    __tablename__ = 'groups'
    id = db.Column(db.String(255), primary_key=True)
    name = db.Column(db.String(16))
    description = db.Column(db.String())

    def create(self):
        db.session.add(self)
        db.session.commit()
    
    def delete(self):
        db.session.delete(self)
        db.session.commit()

aplikasi_chat/website/controllers/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from website.models.user import User
from website import argon2
from flask_login import login_user,login_required,logout_user,current_user
import uuid


auth = Blueprint('auth',__name__)

@auth.route('/')
def home():
    return render_template('homepage.html')

@auth.route('/login',methods=['GET', 'POST'])
def login():
    # Output message if something goes wrong...
    msg = ''
     # Check if "username", "password" and "email" POST requests exist (user submitted form)
    if request.method == 'POST' and 'username' in request.form and 'password':
        # Create variables for easy access
        id = uuid.uuid1()
        username = request.form['username']
        password = request.form['password']
        # Create User object
        user = User.query.filter_by(username=username).first()
        # If account exists show error and validation checks
        if user:
            if(argon2.check_password_hash(user.password, password)):
                # Create session data, we can access this data in other routes
                login_user(user, remember=True)
                # Redirect to user page
                return redirect(url_for('users.home'))
            else:
                # wrong password
                msg = 'Wrong Password'
        else:
            # Account doesnt exist or username incorrect
            msg = "Username Incorrect/Doesn't Exist"
    elif request.method == 'POST':
        # Form is empty... (no POST data)
        msg = 'Please fill out the form!'
    # Show registration form with message (if any)
    return render_template('login.html', msg=msg)

@auth.route('/register',methods=['GET', 'POST'])
def register():
    # Output message if something goes wrong...
    msg = ''
    # Check if "username", "password" and "email" POST requests exist (user submitted form)
    if request.method == 'POST' and 'username' in request.form and 'password' in request.form and 'no_hp' in request.form and 'tanggal_lahir' in request.form:
        # Create variables for easy access
        id = uuid.uuid1()
        username = request.form['username']
        password = argon2.generate_password_hash(request.form['password'])
        no_hp = request.form['no_hp']
        tanggal_lahir = request.form['tanggal_lahir']
        # Create User object
        user = User.query.filter_by(username=username,no_hp=no_hp,tanggal_lahir=tanggal_lahir).first()
        # If account exists show error and validation checks
        if user:
            msg = 'Account already exists!'
        else:
            new_user = User(id=id,username=username,password=password,no_hp=no_hp,tanggal_lahir=tanggal_lahir)
            new_user.create()
            msg = 'You have successfully registered!'
    elif request.method == 'POST':
        # Form is empty... (no POST data)
        msg = 'Please fill out the form!'
    # Show registration form with message (if any)
    return render_template('register.html', msg=msg)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

aplikasi_chat/website/controllers/channels.py
from flask import Blueprint, render_template, request, redirect, url_for,session
from flask_login import login_required,current_user
from website.models.user_group import UserGroup
from website.models.user import User
from website.models.channel import Channel
from website.models.channel_group import ChannelGroup
import uuid
from website import socketio
from flask_socketio import join_room, leave_room, emit

channels = Blueprint('channels',__name__)

@channels.route('/create_channel/<string:id>',methods=['GET', 'POST'])
@login_required
def create_channel(id):
    user = current_user
    # Output message if something goes wrong...
    msg = ''
    # Check if "username" POST requests exist (user submitted form)
    if request.method == 'POST' and 'name' in request.form and 'description' in request.form:
        # Create variables for easy access
        c_id = uuid.uuid1()
        name = request.form['name']
        description = request.form['description']
        new_channel = Channel(id=c_id,name=name,description=description,code=uuid.uuid1())
        user_channel = ChannelGroup(id=uuid.uuid1(),id_group=id,id_channel=c_id)
        user_channel.create()
        new_channel.create()
        msg = 'Channel successfully created!'
        return redirect(url_for('groups.home'))
    elif request.method == 'POST':
        # Form is empty... (no POST data)
        msg = 'Please fill out the form!'
    # Show registration form with message (if any)
    return render_template('Channels/create_channel.html', msg=msg)

@channels.route('/<string:id>',methods=['GET', 'POST'])
@login_required
def manage_group(id):
    user = current_user
    user_Group = UserGroup.query.filter_by(id_group=id,id_user=user.id).first()
    group_channel = Channel.query\
    .join(ChannelGroup,ChannelGroup.id_channel == Channel.id)\
    .filter(ChannelGroup.id_group == id)\
    .add_columns(Channel.name,Channel.id)

    return render_template('Groups/manage_group.html',channels=group_channel,group_id=id,user_group=user_Group)


@channels.route('/chat',methods=['GET','POST'])
@login_required
def chat():
    if request.method == 'POST' and 'id' in request.form:
        # Create variables for easy access
        user = current_user
        id = request.form['id']
        channel = Channel.query.get(id)
        session['channel'] = channel.name
        session['room'] = channel.code
        return render_template('ChatRoom/channel.html', session = session)
    else:
        return redirect(manage_group)


@channels.route('/hapus_channel/<string:group_id>/<string:channel_id>',methods=['GET'])
@login_required
def delete_Channel(group_id,channel_id):
    channel = Channel.query.get(channel_id)
    user_channel = ChannelGroup.query.filter_by(id_channel=channel_id,id_group=group_id).first()
    channel.delete()
    user_channel.delete() 
    return redirect(url_for('groups.home'))

@socketio.on('join', namespace='/channels/chat')
def join(message):
    room = session.get('room')
    join_room(room)


@socketio.on('text', namespace='/channels/chat')
def text(message):
    room = session.get('room')
    emit('message', {'msg': session.get('username') + ' : ' + message['msg']}, room=room)


@socketio.on('left', namespace='/channels/chat')
def left(message):
    room = session.get('room')
    username = session.get('username')
    leave_room(room)
    session.clear()
    emit('status', {'msg': username + ' has left the room.'}, room=room)

aplikasi_chat/website/controllers/groups.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required,current_user
from website.models.group import Group
from website.models.user_group import UserGroup
import uuid

groups = Blueprint('groups',__name__)

@groups.route('/')
@login_required
def home():
    user = current_user
    username =user.username
    user_group_admin = UserGroup.query\
    .join(Group, UserGroup.id_group == Group.id)\
    .filter(UserGroup.id_user == user.id)\
    .add_columns(Group.id,Group.name,Group.description,UserGroup.role)
    return render_template('Groups/main.html',group_admin = user_group_admin, username=username)

@groups.route('/create_group',methods=['GET', 'POST'])
@login_required
def create_group():
    user = current_user
    # Output message if something goes wrong...
    msg = ''
    # Check if "username" POST requests exist (user submitted form)
    if request.method == 'POST' and 'name' in request.form and 'description' in request.form:
        # Create variables for easy access
        id = uuid.uuid1()
        name = request.form['name']
        description = request.form['description']
        new_group = Group(id=id,name=name,description=description)
        user_group = UserGroup(id=uuid.uuid1(),id_user=user.id,id_group=id,role='admin')
        user_group.create()
        new_group.create()
        msg = 'Group successfully created!'
        return redirect(url_for('groups.home'))
    elif request.method == 'POST':
        # Form is empty... (no POST data)
        msg = 'Please fill out the form!'
    # Show registration form with message (if any)
    return render_template('Groups/create_group.html', msg=msg)

@groups.route('/hapus_group/<string:id>',methods=['GET'])
@login_required
def delete_group(id):
    user = current_user
    group = Group.query.get(id)
    user_Group = UserGroup.query.filter_by(id_group=id,id_user=user.id).first()
    group.delete()
    user_Group.delete() 
    return redirect(url_for('groups.home'))



@groups.route('/masuk_group',methods=['GET', 'POST'])
@login_required
def enter_group():
    user = current_user
    # Output message if something goes wrong...
    msg = ''
    # Check if "username" POST requests exist (user submitted form)
    if request.method == 'POST' and 'id_group' in request.form :
        # Create variables for easy access
        id = uuid.uuid1()
        id_group = request.form['id_group']

        group = Group.query.get(id_group)
        user_grup = UserGroup.query.filter_by(id_user=user.id,id_group=id_group).first()
        print(user_grup)
        if( group != None and user_grup == None):
            user_group = UserGroup(id=uuid.uuid1(),id_user=user.id,id_group=id_group,role='user')
            user_group.create()
            return redirect(url_for('groups.home'))
        else:
            msg = "group not found"
    elif request.method == 'POST':
        # Form is empty... (no POST data)
        msg = 'Please fill out the form!'
    # Show registration form with message (if any)
    return render_template('Groups/masuk_group.html', msg=msg)

aplikasi_chat/website/templates/Groups/create_group.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link href="{{ url_for('static',filename='css/creategroup.css') }}"  rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="../static/img/chatpurp-small.png" />
        <title>Chat! Create a New Group</title>
    </head>
    <body>
        <div id="creategroup">
            <div class="container">
                <div id="creategroup-row" class="row justify-content-center align-items-center">
                    <div id="creategroup-column" class="col-md-6">
                        <div id="creategroup-box" class="col-md-12">
                            <form id="register-form" class="form" action="" method="POST">
                                <img src="../static/img/chatgray.png" alt="Logo App-Chat!" width="100" height="70" style="margin-bottom: 15px;">
                                <h3>Create a new Group</h3>
                                <div class="form-group">
                                    <label for="name" class="text-white">NAMA GROUP</label><br>
                                    <input type="text" name="name" id="name" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="description" class="text-white">DESKRIPSI GROUP</label><br>
                                    <input type="text" name="description" id="description" class="form-control">
                                </div>
                                <div class="form-group">
                                    <div class="text-white">{{ msg }}</div>
                                    <input type="submit" class="btn btn-rum form-control" value="Buat Grup">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

aplikasi_chat/website/templates/Groups/main.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link href="{{ url_for('static',filename='css/home.css') }}"  rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="../static/img/chatpurp-small.png" />
        <title>Chat! Group Menu</title>
    </head>
    <body>
      <div class="float-container">

        <div id="welcomebox" class="float-child">
          <div id="logo"><center><img src="../static/img/chatpurp.png" alt="Logo App-Chat!" width="155" height="110"></center></div>
          <div id="username"><h1>Welcome, {{username}}</h1></div>
          <a href="{{ url_for('groups.create_group') }}" class="text-info"><button type="button" class="btn btn-blk form-control" style="margin-top: 30px;">Buat Group</button></a>
          <a href="{{ url_for('groups.enter_group') }}" class="text-info"><button type="button" class="btn btn-blk form-control" style="margin-top: 10px;">Join Group</button></a>
          <center><a href="{{ url_for('auth.logout') }}" class="text-info"><button type="button" class="btn btn-blk" style="margin-top: 30px;">Logout</button></a></center>
          
        </div>
        
        <div class="float-child">
      <div class="container-fluid">
        <h4>Group List</h4>
        <table class="table table-dark">
            <thead>
              <th>Nama Group</th>
            </thead>
            <tbody style="height: 400px; overflow: scroll; display:block;">
              {% for group in group_admin%}
                <tr>
                  <td>{{group['name']}}</td>
                  <td>{{group['description']}}</td>
                  <td> <a href="/channels/{{group['id']}}" class="text-info"><button type="button" class="btn btn-primary" style="font-size: 14px;">Grup</button></a></td>
                  {% if group['role'] == 'admin' %}
                    <td> <a href="/groups/hapus_group/{{group['id']}}" clapss="text-info"><button type="button" class="btn btn-danger" style="font-size: 14px;">Hapus</button></a></td>
                  {% endif %}
                </tr>
              {% endfor %}
            </tbody>
          </table>
            <a href="{{ url_for('users.home') }}" class="text-info"><button type="button" class="btn btn-rum form-control">Friend Menu</button></a>
    </div>
  </div>
</div>
    </body>
</html>

aplikasi_chat/website/templates/Groups/manage_group.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link href="{{ url_for('static',filename='css/managegroup.css') }}"  rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="../static/img/chatpurp-small.png" />
        <title>Chat! Manage Group</title>
    </head>
    <body>
      <div class="float-container">

        <div id="welcomebox" class="float-child">
          <div id="logo"><center><img src="../static/img/chatpurp.png" alt="Logo App-Chat!" width="155" height="110"></center></div>
          <div id="username"><h5>Group Invitation :<br>
            {{ group_id }}
        </h5></div>
            <a href="/channels/create_channel/{{group_id}}" class="text-info"><button type="button" class="btn btn-blk form-control" style="margin-top: 30px;">Buat Channel</button></a>
            <a href="{{ url_for('groups.home') }}" class="text-info"><button type="button" class="btn btn-blk form-control" style="margin-top: 20px;">Kembali ke Menu Group</button></a> 
        <center><a href="{{ url_for('auth.logout') }}" class="text-info"><button type="button" class="btn btn-blk" style="margin-top: 30px;">Logout</button></a></center>
          
        </div>
        
        <div class="float-child">
      <div class="container-fluid">
        <h4>Channel List</h4>
        <table class="table table-dark">
            <thead>
              <th>Nama Channel</th>
            </thead>
            <tbody style="height: 450px; overflow: scroll; display:block;">
              {% for channel in channels%}
                <tr>
                  <td>{{channel['name']}}</td>
                  <td>{{channel['description']}}</td>
                  <td>
                    <form action="{{url_for('channels.chat')}}" method="POST">
                      <input type="hidden" id="id" name="id" value="{{channel['id']}}" >
                      <button class="btn btn-rum" value="submit" style="font-size: 14px;">Start Chat</button>
                    </form></td>
                    {% if user_group['role'] == 'admin' %}
                    <td> <a href="/channels/hapus_channel/{{group_id}}/{{channel['id']}}" clapss="text-info"><button type="button" class="btn btn-danger" style="font-size: 14px;">Hapus</button></a></td>
                  {% endif %}
                </tr>
              {% endfor %}
            </tbody>
          </table>
            
    </div>
  </div>
</div>
    </body>
</html>

aplikasi_chat/website/templates/Groups/masuk_group.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link href="{{ url_for('static',filename='css/creategroup.css') }}"  rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="../static/img/chatpurp-small.png" />
        <title>Chat! Join a Group</title>
    </head>
    <body>
        <div id="creategroup">
            <div class="container">
                <div id="creategroup-row" class="row justify-content-center align-items-center">
                    <div id="creategroup-column" class="col-md-6">
                        <div id="creategroup-box" class="col-md-12">
                            <form id="register-form" class="form" action="" method="POST">
                                <img src="../static/img/chatgray.png" alt="Logo App-Chat!" width="100" height="70" style="margin-bottom: 15px;">
                                <h3>Enter Group Invitation Code</h3>
                                <div class="form-group">
                                    <input type="text" name="id_group" id="id_group" class="form-control">
                                </div>
    
                                <div class="form-group">
                                    <div class="text-white">{{ msg }}</div>
                                    <input type="submit" class="btn btn-rum form-control" value="Join Group">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>