aplikasi_chat/website/controllers/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from website.models.user import User
from website import argon2
from flask_login import login_user,login_required,logout_user,current_user
import uuid


auth = Blueprint('auth',__name__)

@auth.route('/')
def home():
    return render_template('homepage.html')

@auth.route('/login',methods=['GET', 'POST'])
def login():
    # Output message if something goes wrong...
    msg = ''
     # Check if "username", "password" and "email" POST requests exist (user submitted form)
    if request.method == 'POST' and 'username' in request.form and 'password':
        # Create variables for easy access
        id = uuid.uuid1()
        username = request.form['username']
        password = request.form['password']
        # Create User object
        user = User.query.filter_by(username=username).first()
        # If account exists show error and validation checks
        if user:
            if(argon2.check_password_hash(user.password, password)):
                # Create session data, we can access this data in other routes
                login_user(user, remember=True)
                # Redirect to user page
                return redirect(url_for('users.home'))
            else:
                # wrong password
                msg = 'Wrong Password'
        else:
            # Account doesnt exist or username incorrect
            msg = "Username Incorrect/Doesn't Exist"
    elif request.method == 'POST':
        # Form is empty... (no POST data)
        msg = 'Please fill out the form!'
    # Show registration form with message (if any)
    return render_template('login.html', msg=msg)

@auth.route('/register',methods=['GET', 'POST'])
def register():
    # Output message if something goes wrong...
    msg = ''
    # Check if "username", "password" and "email" POST requests exist (user submitted form)
    if request.method == 'POST' and 'username' in request.form and 'password' in request.form and 'no_hp' in request.form and 'tanggal_lahir' in request.form:
        # Create variables for easy access
        id = uuid.uuid1()
        username = request.form['username']
        password = argon2.generate_password_hash(request.form['password'])
        no_hp = request.form['no_hp']
        tanggal_lahir = request.form['tanggal_lahir']
        # Create User object
        user = User.query.filter_by(username=username,no_hp=no_hp,tanggal_lahir=tanggal_lahir).first()
        # If account exists show error and validation checks
        if user:
            msg = 'Account already exists!'
        else:
            new_user = User(id=id,username=username,password=password,no_hp=no_hp,tanggal_lahir=tanggal_lahir)
            new_user.create()
            msg = 'You have successfully registered!'
    elif request.method == 'POST':
        # Form is empty... (no POST data)
        msg = 'Please fill out the form!'
    # Show registration form with message (if any)
    return render_template('register.html', msg=msg)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

aplikasi_chat/website/controllers/users.py
from website.models.user_blocked import BlockedUser
from flask import Blueprint, render_template, request, redirect, url_for, session
from flask_login import login_required,current_user
from website.models.user_friend import UserFriend
from website.models.user import User
from website.models.user_blocked import BlockedUser
from website import socketio
from flask_socketio import join_room, leave_room, emit
import uuid

users = Blueprint('users',__name__)

@users.route('/')
@login_required
def home():
    user = current_user
    username =user.username
    blocked_user = BlockedUser.query\
    .join(User, BlockedUser.id_user_blocked == User.id)\
    .filter(BlockedUser.id_user == user.id)\
    .add_columns(User.username,BlockedUser.id)
    
    user_teman = UserFriend.query\
    .join(User, UserFriend.id_user == User.id)\
    .filter(UserFriend.id_user_teman == user.id)\
    .add_columns(User.username,UserFriend.id)
    return render_template('AddFriend/main.html',friends=user_teman,blocked=blocked_user,username=username)

@users.route('/tambah_teman',methods=['GET', 'POST'])
@login_required
def add_new_friend():
    # Output message if something goes wrong...
    msg = ''
    # Check if "username" POST requests exist (user submitted form)
    if request.method == 'POST' and 'username' in request.form:
        # Create variables for easy access
        username = request.form['username']
        # Check if account exists using MySQL
        user_friend = User.query.filter_by(username=username).first()
        user = current_user
        # If account exists show error and validation checks
        if not user_friend:
            msg = 'Account do not exists!'
        elif not username:
            msg = 'Please fill out the form!'
        else:
            user_room = uuid.uuid1()
            add_user_friend = UserFriend(id = uuid.uuid1(),id_user=user.id,id_user_teman=user_friend.id,user_room=user_room)
            add_user_friend.create()
            add_user_friend = UserFriend(id = uuid.uuid1(),id_user=user_friend.id,id_user_teman=user.id,user_room=user_room)
            add_user_friend.create()
            return redirect(url_for('users.home'))
    elif request.method == 'POST':
        # Form is empty... (no POST data)
        msg = 'Please fill out the form!'
    # Show registration form with message (if any)
    return render_template('AddFriend/add_new_friend.html', msg=msg)

@users.route('/hapus_teman/<string:id>',methods=['GET'])
@login_required
def delete_friend(id):
    user = current_user
    user_friend = UserFriend.query.get(id)
    get_user_friend = UserFriend.query.filter_by(id_user=user.id,id_user_teman=user_friend.id_user).first()
    user_friend.delete()
    get_user_friend.delete() 
    return redirect(url_for('users.home'))

@users.route('/blokir_teman/<string:id>',methods=['GET'])
@login_required
def blocked_user(id):
    user = current_user
    user_friend = UserFriend.query.get(id)
    get_user_friend = UserFriend.query.filter_by(id_user=user.id,id_user_teman=user_friend.id_user).first()
    bloked_friend = BlockedUser(id=uuid.uuid1(),id_user=user.id,id_user_blocked=user_friend.id_user)
    bloked_friend.create()
    user_friend.delete()
    get_user_friend.delete() 
    return redirect(url_for('users.home'))

@users.route('/unblokir_teman/<string:id>',methods=['GET'])
@login_required
def unblocked_user(id):
    user = current_user
    blocked_friend = BlockedUser.query.get(id)
    user_friend = User.query.filter_by(id=blocked_friend.id_user_blocked).first()
    user_room = uuid.uuid1()
    add_user_friend = UserFriend(id = uuid.uuid1(),id_user=user.id,id_user_teman=user_friend.id,user_room=user_room)
    add_user_friend.create()
    add_user_friend = UserFriend(id = uuid.uuid1(),id_user=user_friend.id,id_user_teman=user.id,user_room=user_room)
    add_user_friend.create()
    blocked_friend.delete()

    return redirect(url_for('users.home'))

@users.route('/chat',methods=['GET','POST'])
@login_required
def chat():
    if request.method == 'POST' and 'id' in request.form:
        # Create variables for easy access
        id = request.form['id']
        user = current_user
        user_friend = UserFriend.query.get(id)
        session['username'] = user.username
        session['room'] = user_friend.user_room
        return render_template('ChatRoom/main.html', session = session)
    else:
        return render_template('ChatRoom/main.html', session = session)

@socketio.on('join', namespace='/users/chat')
def join(message):
    room = session.get('room')
    join_room(room)


@socketio.on('text', namespace='/users/chat')
def text(message):
    room = session.get('room')
    emit('message', {'msg': session.get('username') + ' : ' + message['msg']}, room=room)


@socketio.on('left', namespace='/users/chat')
def left(message):
    room = session.get('room')
    username = session.get('username')
    leave_room(room)
    session.clear()
    emit('status', {'msg': username + ' has left the room.'}, room=room)

aplikasi_chat/website/templates/AddFriend/add_new_friend.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link href="{{ url_for('static',filename='css/addfriend.css') }}"  rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="../static/img/chatpurp-small.png" />
        <title>Chat! Add Friend via Username</title>
    </head>
    <body>
        <div id="addfriend">
            <div class="container">
                <div id="addfriend-row" class="row justify-content-center align-items-center">
                    <div id="addfriend-column" class="col-md-6">
                        <div id="addfriend-box" class="col-md-12">
                            <form id="register-form" class="form" action="" method="POST">
                                <img src="../static/img/chatgray.png" alt="Logo App-Chat!" width="100" height="70" style="margin-bottom: 15px;">
                                <h4>Enter Username you want to add as Friend</h4>
                                <div class="form-group">
                                    <input type="text" name="username" id="username" class="form-control">
                                </div>
                                <div class="form-group">
                                    <div class="text-white">{{ msg }}</div>
                                    <input type="submit" class="btn btn-rum form-control" value="Add Friend">
                                 </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

aplikasi_chat/website/templates/AddFriend/main.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link href="{{ url_for('static',filename='css/home.css') }}"  rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="../static/img/chatpurp-small.png" />
        <title>Chat! Home</title>
    </head>
    <body>
      <div class="float-container">

        <div id="welcomebox" class="float-child">
          <div id="logo"><center><img src="../static/img/chatpurp.png" alt="Logo App-Chat!" width="155" height="110"></center></div>
          <div id="username"><h1>Welcome, {{username}}</h1></div>
          <center><a href="{{ url_for('auth.logout') }}" class="text-info"><button type="button" class="btn btn-blk" style="margin-top: 30px;">Logout</button></a></center>
          
        </div>
        
        <div class="float-child">
          <div class="container-fluid">
            <h4>Friend List
              <a href="{{ url_for('users.add_new_friend') }}" class="text-info"><button type="button" class="btn btn-rum">Tambah Teman</button></a>
            </h4>
            <table class="table table-dark">
                <thead>
                  <td>Username</td>
                </thead>
                <tbody style="height: 200px; overflow: auto; display:block">
                    {% for friend in friends%}
                    <tr>
                      <td>{{friend['username']}}</td>
                      <td> <a href="/users/hapus_teman/{{friend['id']}}" class="text-info"><button type="button" class="btn btn-danger" style="font-size: 14px;">Hapus</button></a></td>
                      <td> <a href="/users/blokir_teman/{{friend['id']}}" class="text-info"><button type="button" class="btn btn-danger" style="font-size: 14px;">Blokir</button></a></td>
                      <td>  <form action="{{url_for('users.chat')}}" method="POST">
                        <input type="hidden" id="id" name="id" value="{{friend['id']}}" >
                        <button class="btn btn-rum" value="submit" style="font-size: 14px;">Start Chat</button>
                      </form></td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
                <h4>Blocked User (Friend) List</h4>
                <table class="table table-dark">
                  <thead>
                    <td>Username</td>
                  </thead>
                  <tbody style="height: 100px; overflow: auto; display:block">
                      {% for block in blocked%}
                      <tr>
                        <td>{{block['username']}}</td>
                        <td> <a href="/users/unblokir_teman/{{block['id']}}" class="text-info"><button type="button" class="btn btn-rum" style="font-size: 14px;">Unblokir</button></a></td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
                <a href="{{ url_for('groups.home') }}" class="text-info"><button type="button" class="btn btn-rum form-control">Group Menu</button></a>
            </div>
          </div>
      </div>
    </body>
    
</html>