aplikasi_chat/website/models/channel.py
from website import db

class Channel(db.Model):
    __tablename__ = 'channels'
    id = db.Column(db.String(255), primary_key=True)
    name = db.Column(db.String(16))
    description = db.Column(db.String())
    code = db.Column(db.String(255))

    def create(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

aplikasi_chat/website/controllers/channels.py
from flask import Blueprint, render_template, request, redirect, url_for,session
from flask_login import login_required,current_user
from website.models.user_group import UserGroup
from website.models.user import User
from website.models.channel import Channel
from website.models.channel_group import ChannelGroup
import uuid
from website import socketio
from flask_socketio import join_room, leave_room, emit

channels = Blueprint('channels',__name__)

@channels.route('/create_channel/<string:id>',methods=['GET', 'POST'])
@login_required
def create_channel(id):
    user = current_user
    # Output message if something goes wrong...
    msg = ''
    # Check if "username" POST requests exist (user submitted form)
    if request.method == 'POST' and 'name' in request.form and 'description' in request.form:
        # Create variables for easy access
        c_id = uuid.uuid1()
        name = request.form['name']
        description = request.form['description']
        new_channel = Channel(id=c_id,name=name,description=description,code=uuid.uuid1())
        user_channel = ChannelGroup(id=uuid.uuid1(),id_group=id,id_channel=c_id)
        user_channel.create()
        new_channel.create()
        msg = 'Channel successfully created!'
        return redirect(url_for('groups.home'))
    elif request.method == 'POST':
        # Form is empty... (no POST data)
        msg = 'Please fill out the form!'
    # Show registration form with message (if any)
    return render_template('Channels/create_channel.html', msg=msg)

@channels.route('/<string:id>',methods=['GET', 'POST'])
@login_required
def manage_group(id):
    user = current_user
    user_Group = UserGroup.query.filter_by(id_group=id,id_user=user.id).first()
    group_channel = Channel.query\
    .join(ChannelGroup,ChannelGroup.id_channel == Channel.id)\
    .filter(ChannelGroup.id_group == id)\
    .add_columns(Channel.name,Channel.id)

    return render_template('Groups/manage_group.html',channels=group_channel,group_id=id,user_group=user_Group)


@channels.route('/chat',methods=['GET','POST'])
@login_required
def chat():
    if request.method == 'POST' and 'id' in request.form:
        # Create variables for easy access
        user = current_user
        id = request.form['id']
        channel = Channel.query.get(id)
        session['channel'] = channel.name
        session['room'] = channel.code
        return render_template('ChatRoom/channel.html', session = session)
    else:
        return redirect(manage_group)


@channels.route('/hapus_channel/<string:group_id>/<string:channel_id>',methods=['GET'])
@login_required
def delete_Channel(group_id,channel_id):
    channel = Channel.query.get(channel_id)
    user_channel = ChannelGroup.query.filter_by(id_channel=channel_id,id_group=group_id).first()
    channel.delete()
    user_channel.delete() 
    return redirect(url_for('groups.home'))

@socketio.on('join', namespace='/channels/chat')
def join(message):
    room = session.get('room')
    join_room(room)


@socketio.on('text', namespace='/channels/chat')
def text(message):
    room = session.get('room')
    emit('message', {'msg': session.get('username') + ' : ' + message['msg']}, room=room)


@socketio.on('left', namespace='/channels/chat')
def left(message):
    room = session.get('room')
    username = session.get('username')
    leave_room(room)
    session.clear()
    emit('status', {'msg': username + ' has left the room.'}, room=room)

aplikasi_chat/website/templates/Channels/create_channel.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link href="{{ url_for('static',filename='css/creategroup.css') }}"  rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="../static/img/chatpurp-small.png" />
        <title>Chat! Create a New Channel</title>
    </head>
    <body>
        <div id="creategroup">
            <div class="container">
                <div id="creategroup-row" class="row justify-content-center align-items-center">
                    <div id="creategroup-column" class="col-md-6">
                        <div id="creategroup-box" class="col-md-12">
                            <form id="register-form" class="form" action="" method="POST">
                                <img src="../../static/img/chatgray.png" alt="Logo App-Chat!" width="100" height="70" style="margin-bottom: 15px;">
                                <h3>Create a new Channel</h3>
                                <div class="form-group">
                                    <label for="name" class="text-white">NAMA CHANNEL</label><br>
                                    <input type="text" name="name" id="name" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="description" class="text-white">DESKRIPSI CHANNEL</label><br>
                                    <input type="text" name="description" id="description" class="form-control">
                                </div>
                                <div class="form-group">
                                    <div class="text-white">{{ msg }}</div>
                                    <input type="submit" class="btn btn-rum form-control" value="Buat Channel">
                                </div>
                                <a href="javascript:history.back()">Go Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

aplikasi_chat/website/templates/Channels/main.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link href="{{ url_for('static',filename='css/register.css') }}"  rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="../static/img/chatpurp-small.png" />
        <title>Chat! Create a Channel</title>
    </head>
    <body>
        <tbody>
            {% for channel in channels%}
            <tr>
              <td>{{channel['name']}}</td>
              <td> <a href="{{ url_for('channels.create_channel') }}/{{url_for('channels.create_channel')}}" class="text-info"><button type="button" class="btn btn-primary">Buat Channel Baru</button></a></td>
              <form action="{{url_for('channels.chat')}}" method="POST">
                <input type="hidden" id="id" name="id" value="{{channel['id']}}" >
                <button class="btn btn-rum" value="submit" style="font-size: 14px;">Start Chat</button>
              </form></td>
            </tr>
          {% endfor %}
        </tbody>
    </body>
</html>